### ISSUE TITLE
Using style lint with .sass files

### ISSUE THREAD

**Issue by Daweo93** [kristerkari/stylelint-scss#104]
Hello,
Is there any way to use stylelint for lint .sass files?
It's works for .scss files fine but I use .sass files.

**Comment by dryoma** [comment]
Hi @Daweo93 

If you mean Sass syntax, then I'm afraid no, stylelint and this plugin set can't be used with it. You'd have to stick to https://github.com/sasstools/sass-lint or look for some other tool.

**Comment by kristerkari** [comment]
Thanks for the question @Daweo93

I think there is no `Sass` syntax parser for PostCSS (which is used by Stylelint). This project is only for linting Sass' `Scss` syntax, and that's also why the name is `stylelint-scss`.

**Comment by jeddy3** [comment]
@Daweo93 Another alternative is to migrate from SASS to [SugarSS](https://github.com/postcss/sugarss), which is an _indent-based_ syntax similar to SASS. 

stylelint is compatible with SugarSS.

**Comment by kristerkari** [comment]
@jeddy3 I noticed this tweet. Will stylelint support sass-syntax too?
https://twitter.com/PostCSS/status/842110688118095873

**Comment by jeddy3** [comment]
> I noticed this tweet

I just saw that too! Interesting stuff.

> Will stylelint support sass-syntax too?

I not sure if it'll have _first-class_ support (i.e. we bundle the parser in stylelint). However, [we provide](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/cli.md) a `--custom-syntax` option that you can use to try out sass-syntax now:

> Additionally, stylelint can accept a custom PostCSS-compatible syntax. To use a custom syntax, supply a syntax module name or path to the syntax file: `--custom-syntax custom-syntax` or `--custom-syntax ./path/to/custom-syntax`.

> Note, however, that stylelint can provide no guarantee that core rules will work with syntaxes other than the defaults listed above

So:

```console
npm i -D AleshaOleg/postcss-sass
stylelint "**/*.sass" --custom-syntax postcss-sass
```

I've not tried it myself.

**Comment by ntwb** [comment]
FYI: PostCSS now has a Sass parser [postcss-sass](https://github.com/AleshaOleg/postcss-sass)

See also: https://github.com/stylelint/stylelint/issues/2486

**Comment by evilebottnawi** [comment]
@kristerkari can be close, stylelint support `sass`, rules for `sass` better store in other repos :smile:

**Comment by Grawl** [comment]
`postcss-sass` is not finished yet. here's my repository for testing: https://github.com/Grawl/stylelint-sass-test
