### ISSUE TITLE
at-mixin-argumentless-call-parentheses rule is showing up severity: "ignore"

### ISSUE THREAD

**Issue by LukaszPrzybysz** [kristerkari/stylelint-scss#106]
Hey,
I have seen that such a bug was already resolved in version 1.1.0 but it still occurs in at-mixin-argumentless-call-parentheses rule.

**Comment by dryoma** [comment]
Hi @LukaszPrzybysz 

Could you please describe the issue in a more detail? What is the stylelint config, stylelint/stylelint-scss/node versions, your code. What exactly happened (your actions and the error message), and what was expected.

**Comment by LukaszPrzybysz** [comment]
I have actually found a bug, there is incorrect ruleName set in:
`src/rules/at-mixin-argumentless-call-parentheses/index.js`
