### ISSUE TITLE
at-if-closing-brace-newline-after only checks for else and not elseif

### ISSUE THREAD

**Issue by rvock** [kristerkari/stylelint-scss#107]
If you use the `at-if-closing-brace-newline-after` rule with `always-last-in-chain` the following code generates an error:
```scss
@if $min and $max {
	$range: '(#{$min} - #{$max})';
} @elseif $max {
	$range: '(< #{$max})';
} @else {
	$range: '(> #{$min})';
}
```

The happens because elseif is not checked. Although not documented in the [sass-documentation](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#_8) `@elseif` is supported in scss.

The code to update is here:
https://github.com/kristerkari/stylelint-scss/blob/483052/src/rules/at-if-closing-brace-newline-after/index.js#L62

**Comment by kristerkari** [comment]
Sorry for the late answer, but I have been busy. 

I added a fix for this, you can check out the Pull request that should fix this issue:
https://github.com/kristerkari/stylelint-scss/pull/110
