### ISSUE TITLE
Deprecated `stylelint-rule-tester`, switch to `stylelint-test-rule-tape`

### ISSUE THREAD

**Issue by ntwb** [kristerkari/stylelint-scss#11]
[stylelint-rule-tester](https://github.com/stylelint/stylelint-rule-tester) has been deprecated in favour of  [stylelint-test-rule-tape](https://github.com/stylelint/stylelint-test-rule-tape)

See https://github.com/stylelint/stylelint-rule-tester/issues/9

See also an example of the switch https://github.com/davidtheclark/stylelint-selector-bem-pattern/commit/796ad6cd9512884576e938ba1f18c9525e5b2e2e

**Comment by kristerkari** [comment]
Thanks! stylelint moves so fast that it's hard to keep things up-to-date :)

**Comment by jeddy3** [comment]
> stylelint moves so fast

Yep. If it's any help:

1. We're going to be slowing things down a little :)
2. It's *very unlikely* the rule tester will change again. Adding the schema [was a major change](https://github.com/stylelint/stylelint/pull/824) which allowed the FB guys to use jest for their tests. So, once you migrate to the schema, you should be done.

**Comment by dryoma** [comment]
New testing tool applied. Moving on.

**Comment by kristerkari** [comment]
👍 Thanks @dryoma
