### ISSUE TITLE
Rule idea: mixin-name-pattern, function-name-pattern

### ISSUE THREAD

**Issue by dryoma** [kristerkari/stylelint-scss#12]
Or `mixin-pattern`, `function-pattern` to follow the existing stylelint [rule naming conventions](http://stylelint.io/user-guide/rules/).

stylelint-scss already has a rule for placeholder names, the one for variable names is in a PR now. The subject rules are the ones missing. SCSS-lint has those (though in a format of [one general naming rule for Sass stuff](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#nameformat)). I could take implementing them, seems not that hard.

The only question I have: should some general patterns like `lowercase-underscore`, etc. be imlpemented as predefined primary option values (like in SCSS-lint)? If yes, what predefined patterns would you recommend to use?

**Comment by dryoma** [comment]
Another thing that came to mind is maybe these rules should have `sass-`/`scss-` prefix? So that they don't conflict with other rules written for other preprocessors, and also don't misguide users on what preprocessor/technology they rely.

**Comment by kristerkari** [comment]
> Another thing that came to mind is maybe these rules should have sass-/scss- prefix?

Yes, that can be done before releasing v1.0. I'll add that to the release checklist.

**Comment by kristerkari** [comment]
> The only question I have: should some general patterns like lowercase-underscore, etc. be imlpemented as predefined primary option values (like in SCSS-lint)? If yes, what predefined patterns would you recommend to use?

Does stylelint use default options in rules? I think that we should try to keep things consistent with it and not with SCSS-lint.

**Comment by dryoma** [comment]
I thougth that too (stylelint doesn't have predefined patterns for its core rules), but decided to suggest just in case.

**Comment by jeddy3** [comment]
> Does stylelint use default options in rules? 

As you both spotted, there are no default primary options for stylelint rules. It was a conscience decision to both keeps the rules unopinionated and to mitigate having to deliberate on what the defaults options should be :)

**Comment by jeddy3** [comment]
> Another thing that came to mind is maybe these rules should have sass-/scss- prefix?

This is tricky as I suspect quite a few of these rules will be applicable to [precss](https://github.com/jonathantneal/precss) users (or some other future processor). Hence the original suggestion of `dollar-variable-pattern`, rather than `scss-variable-pattern`. There could also be a plugin for Less users called `at-variable-pattern`.

I dunno if there's a right answer here though.

**Comment by kristerkari** [comment]
> This is tricky as I suspect quite a few of these rules will be applicable to precss users (or some other future processor). Hence the original suggestion of dollar-variable-pattern, rather than scss-variable-pattern. There could also be a plugin for Less users called at-variable-pattern.

Yeah, it is true that some of the rules can be used with other post/preprocessors.

However, I see some issues if we don't prefix the rules:
- It is probably harder for the users to know from where their stylelint rules are coming from.
- It might be possible that someone creates a rule in some other plugin that has the same name, but does something totally different.

**Comment by dryoma** [comment]
> `dollar-variable-pattern`
`at-variable-pattern`

Then how about `at-mixin-pattern` and `at-function-pattern`? Quite straightforward and doesn't narrow semantics of the names to Sass alone.

> There's no harm in documenting those regexs though in the READMEs though.
That would be a good compromise, thanks!

**Comment by jeddy3** [comment]
> Then how about `at-mixin-pattern` and `at-function-pattern`? Quite straightforward and doesn't narrow semantics of the names to Sass alone.

Sounds good to me :)

@kristerkari Your points are valid, but I think keeping rules focused on patterns (rather than parsers) will help keep the linter (and this plugin) relevant as the CSS processor world continues to evolve.

**Comment by kristerkari** [comment]
> Your points are valid, but I think keeping rules focused on patterns (rather than parsers) will help keep the linter (and this plugin) relevant as the CSS processor world continues to evolve.

I'm starting to think that maybe this repo should have a different name if the rules are not going to be parser specific. It sounds weird to me that you would use `stylelint-scss` to lint against something that is not scss. Any suggestions?

Maybe this plugin should also handle edge cases for other parsers (LESS, postcss plugins)?

**Comment by jeddy3** [comment]
> Any suggestions?

`stylelint-scss-like` :)

> Maybe this plugin should also handle edge cases for other parsers (LESS, postcss plugins)?

That sounds sensible. There probably won't be much overlap with Less, but I think they'll be plenty with postcss plugins (with the likes of [precss](https://github.com/jonathantneal/precss) and [these language extensions](https://github.com/postcss/postcss/blob/master/docs/plugins.md#language-extensions)). I think no longer relying on developer discipline by [crafting your own processor](http://davidtheclark.com/excited-about-postcss/#mature-and-monolithic-or-fresh-and-modular) is going to become more popular, and so supporting this approach might add a bit more longevity to this project.
