### ISSUE TITLE
Mixin-name-pattern is not working for postcss-mixins

### ISSUE THREAD

**Issue by sourav-kumar** [kristerkari/stylelint-scss#121]
Postcss-mixin is having differnt way to write and add mixin,

Is there any way we can validate those syntax ?

**Comment by kristerkari** [comment]
Thanks for the question.

I see that this was already answered in https://github.com/stylelint/stylelint/issues/2600#issuecomment-304978387, so I'd also say that a custom plugin is a good idea. Closing this for now.
