### ISSUE TITLE
recommended configuration [feature request]

### ISSUE THREAD

**Issue by damianobarbati** [kristerkari/stylelint-scss#123]
Is there a way to require all the rules at once?
Like:
```
            styleLint({
                extends: ['stylelint-config-standard', 'plugin:scss/recommended'],
                plugins: ['stylelint-scss'],
            }),

```

**Comment by kristerkari** [comment]
This is a duplicate of https://github.com/kristerkari/stylelint-scss/issues/91, so let's continue the discussion there.

We haven't made a standard config yet because someone needs to decide which rules to include.
