### ISSUE TITLE
Suggestion: Add rule "at-rule-no-unknown"

### ISSUE THREAD

**Issue by lithiumlron** [kristerkari/stylelint-scss#126]
This issue was discussed previously in #86 and PR #92 was created to resolve the issue but before stylelint/stylelint#2173 was released.

With stylelint/stylelint#2173 resolved using `stylelint.utils.checkAgainstRule` in stylelint ^7.7.0, perhaps this rule can be added now?

I have a working implementation in my [fork under branch "at-rule-unknown"](https://github.com/lithiumlron/stylelint-scss/tree/at-rule-no-unknown) with tests (from #92) all passing.

**Comment by kristerkari** [comment]
Yeah it has been on hold because https://github.com/kristerkari/stylelint-scss/pull/92 has not been finished.

Please submit a PR if you have got a working implementation 👍
