### ISSUE TITLE
at-rule-no-unknow: Cannot read property 'rejected' of undefined

### ISSUE THREAD

**Issue by weaintplastic** [kristerkari/stylelint-scss#145]
Hey, 

I'm getting the following error with the latests release when executing stylelint. 
```
TypeError: Cannot read property 'rejected' of undefined
npm ERR!     at Object.<anonymous> (/node_modules/stylelint-scss/dist/rules/at-rule-no-unknown/index.js:62:58)
```

**Comment by kristerkari** [comment]
Hmm.. @weaintplastic which versions of `stylelint` and `stylelint-scss` are you using?

**Comment by weaintplastic** [comment]
My fault, sorry. I was still on a locked outdated version of stylelint. I'm very sorry.
