### ISSUE TITLE
Order?

### ISSUE THREAD

**Issue by corysimmons** [kristerkari/stylelint-scss#159]
Can you use this plugin to put SCSS concepts (like vars, mixins, etc.) in *order* like:

```
.ruleset {
  $variables: blue;

  @includes foo();

  properties: orange;

  @media (min-width: 10px) {
    $variables: pink;

    @includes bar();

    properties: orange;
  }
}
```

**Comment by kristerkari** [comment]
@corysimmons nope, but you can use [stylelint-order](https://github.com/hudochenkov/stylelint-order) or [postcss-sorting](https://github.com/hudochenkov/postcss-sorting) to do just that.

**Comment by corysimmons** [comment]
Yeah, sorry, I overlooked https://github.com/hudochenkov/stylelint-order/blob/master/rules/order/README.md#options

Thank you!
