### ISSUE TITLE
Rule idea: at-rule-import-path

### ISSUE THREAD

**Issue by evilebottnawi** [kristerkari/stylelint-scss#19]
https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#importpath

**Comment by kristerkari** [comment]
Thanks! Sounds good, I'll add this to the next milestone.

**Comment by jeddy3** [comment]
Perhaps called `at-import-no-invalid-partial-path`?

`at-rules-*` rules [tend to apply to all at-rules](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#at-rule), rather than a specific type.

**Comment by dryoma** [comment]
@jeddy3 I'm actually thinking of making this two separate rules: `at-import-no-partial-leading-underscore` and `at-import-no-partial-extension`. The last one might take an array of extensions to forbid (`["scss", "less"]`).

**Comment by jeddy3** [comment]
> I'm actually thinking of making this into two separate rules: at-import-no-partial-leading-underscore and at-import-no-partial-extension.

Breaking this into two rules sounds good to me! You're getting better at this than me :)

> The last one might take an array of extensions to forbid (["scss", "less"]).

`no-*` rules tend to only have `true` as the primary options. So, in this instance, you can either use a blacklist rule or `no-` rule with [secondary option](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#determine-options) *that makes the rule more permissive* e.g. respectively:

- `at-import-partial-extension-blacklist: []`
- `at-import-no-partial-extension: [ true, { ignoreExtensions: ["less"] } ]` - where `ignoreExtensions` is a *user-defined* list of extensions to ignore.

I'm going to be on holiday for the next couple of weeks, and so I figured I'd feedback on these upcoming rules before I go. Great job with `1.0.0` btw :)

**Comment by dryoma** [comment]
> Breaking this into two rules sounds good to me

Thanks. I'm just working on a project where Sass partials and bootstrap files (and even CSS) of the same name can be in the same directory, so we sometimes have to specifically tell Sass what exactly we are importing.

> `no-*` rules tend to only have true as the primary options

Sure, didn't pay attention to the name while writing. Yeah, the `no-` variant looks better to me (easier to set up). But since Sass treats `@import`-s with `.css` [as simple CSS directives](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#import), we'll have to ignore `.css` extension by default (I wouldn't like to force a user to add it manually).

> Great job with 1.0.0 btw :)

Тhanks again! Yet so much to do be done %)

**Comment by jeddy3** [comment]
> But since Sass treats @import-s with .css as simple CSS directives, we'll have to ignore .css extension by default (I wouldn't like to force a user to add it manually).

Agreed. I figured that is implied by the fact the rule name has "partial" in it. Either way, explicitly stating in the rule's README that this is the behaviour should be enough :)

**Comment by el-mapache** [comment]
Hey @dryoma, hello from 18F! @jeddy3 reached out to me about potentially combining our efforts re: stylelint plugins. I've recently written some, including a couple around `@import` rules. I'd love to work with you all on contributing these back to the community.
Our repo can be found here: https://github.com/18F/18F-stylelint

Any comments, suggestions, edge-cases, PRs, etc. are more than welcome!

Just as a quick FYI, all of our code is released in the public domain under CC0. You can find information about it in the LICENSE file in the repo.

Thanks!

**Comment by kristerkari** [comment]
@el-mapache Hello! We should definitely combine efforts since you already have something that could be useful for this project.

**Comment by dryoma** [comment]
@el-mapache hi! That would be nice, will check your code in a while :)

I already pushed a PR with `@import` rules. As for those in *18F-stylelint*: I'm sorry, but they seem a bit raw. `import-path-leading-underscore` doesn't consider file paths (e.g. `@import "path/to/_partial"`) and cases when Sass considers an `@import` just plain CSS import discussed above.

**Comment by dryoma** [comment]
Implemented by #27
