### ISSUE TITLE
dollar-variable-colon-space-after: At least one space

### ISSUE THREAD

**Issue by jblandry** [kristerkari/stylelint-scss#195]
Would it be complex to add the possibility of having at least one space after the colon, for the purpose of aligning values ?
```
$base-color:     #ff0000;
$primary-color:  #00ff00;
$alt-color:      #0000ff;
```
Ref: [SCSS Lint at_least_one_space](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#spaceaftervariablecolon)

**Comment by kristerkari** [comment]
Thanks @jblandry! That could be implemented as a new rule, why not :)

**Comment by jblandry** [comment]
🎉

**Comment by stormwarning** [comment]
Hmm, I'm getting

```Invalid Option: Invalid option value "at-least-one-space" for rule "scss/dollar-variable-colon-space-after"```

after adding the new option to my `.stylelintrc.js` but I can't figure out why...

**Comment by kristerkari** [comment]
@stormwarning make sure that you have the latest version installed.

Works for me with:

```
"scss/dollar-variable-colon-space-after": "at-least-one-space"
```

**Comment by stormwarning** [comment]
Yeah, looks like the latest is in `node_modules` 🤷‍♂️ Must be something with this specific project I guess. Thanks for confirming it's working!

**Comment by jblandry** [comment]
Implemented! Thanks a lot 👍 
https://github.com/absolunet/stylelint-config-nwayo/blob/master/.stylelintrc.yaml#L501

**Comment by kristerkari** [comment]
Nice to hear @jblandry. :) Let us know if you find any bugs related to that rule or any other rules.
