### ISSUE TITLE
Support `stylelint@9`

### ISSUE THREAD

**Issue by evilebottnawi** [kristerkari/stylelint-scss#209]
:star:

**Comment by kristerkari** [comment]
Definitely, it's a good time to drop Node 4 support too, https://github.com/kristerkari/stylelint-scss/pull/194.

**Comment by evilebottnawi** [comment]
@kristerkari +1

**Comment by kristerkari** [comment]
I'm planning on doing this in 2 steps. 

First release a minor version that adds support for stylelint 9. Next version after that could be a major version (3.0)  that drops support for Node.js 4.

**Comment by evilebottnawi** [comment]
@kristerkari sound good

**Comment by kristerkari** [comment]
Done:
https://github.com/kristerkari/stylelint-scss/releases/tag/2.4.0
