### ISSUE TITLE
[Request] ignore some function names for `at-function-named-arguments`

### ISSUE THREAD

**Issue by chimericdream** [kristerkari/stylelint-scss#242]
I'd like to require named arguments for most function calls, but exclude things like `map-merge()`. Would it be possible to add this as an optional secondary rule?

**Comment by chrisopedia** [comment]
On the same vein here, how would you deal with things like:

```
str-replace(url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='592' height='90' viewBox='0 0 592 90'%3E%3Cpath fill='#{$placeholder-color}' fill-rule='evenodd' d='M3 0h94a3 3 0 0 1 3 3v24a3 3 0 0 1-3 3H3a3 3 0 0 1-3-3V3a3 3 0 0 1 3-3zm0 60h94a3 3 0 0 1 3 3v24a3 3 0 0 1-3 3H3a3 3 0 0 1-3-3V63a3 3 0 0 1 3-3zM167 0h94a3 3 0 0 1 3 3v24a3 3 0 0 1-3 3h-94a3 3 0 0 1-3-3V3a3 3 0 0 1 3-3zm0 60h94a3 3 0 0 1 3 3v24a3 3 0 0 1-3 3h-94a3 3 0 0 1-3-3V63a3 3 0 0 1 3-3zM331 0h94a3 3 0 0 1 3 3v24a3 3 0 0 1-3 3h-94a3 3 0 0 1-3-3V3a3 3 0 0 1 3-3zm0 60h94a3 3 0 0 1 3 3v24a3 3 0 0 1-3 3h-94a3 3 0 0 1-3-3V63a3 3 0 0 1 3-3zM495 0h94a3 3 0 0 1 3 3v24a3 3 0 0 1-3 3h-94a3 3 0 0 1-3-3V3a3 3 0 0 1 3-3zm0 60h94a3 3 0 0 1 3 3v24a3 3 0 0 1-3 3h-94a3 3 0 0 1-3-3V63a3 3 0 0 1 3-3z'/%3E%3C/svg%3E"), "#", "%23");
```

**Comment by kristerkari** [comment]
@chrisopedia That looks like a bug to me. I'll investigate

**Comment by kristerkari** [comment]
Just to give an update, I have verified the bug and I'm working on a fix. It's a bit tricky to fix tho because of the hacky way of how the rule is parsing function parameters currently.

**Comment by kristerkari** [comment]
@chrisopedia Here's the pull request with a fix: https://github.com/kristerkari/stylelint-scss/pull/267

I'll release a new version after that gets merged.

**Comment by kristerkari** [comment]
@chimericdream I have implemented an option called `ignoreFunctions`. It will be included in the next release: https://github.com/kristerkari/stylelint-scss/pull/269

**Comment by kristerkari** [comment]
Both things are included in the latest release:
https://github.com/kristerkari/stylelint-scss/releases/tag/3.3.0
