### ISSUE TITLE
Rule idea: Disallow Sass variables

### ISSUE THREAD

**Issue by sindresorhus** [kristerkari/stylelint-scss#243]
I use a lot of Sass features, but I can't use Sass variables as they are resolved at compile time, which doesn't work with how I do theming, so I need to use CSS variables. Would be nice to be able to disallow Sass variables so I don't accidentally use them.

**Comment by kristerkari** [comment]
This would probably then go to the section `General / Sheet` and would be called `no-dollar-variables`.
