### ISSUE TITLE
Rule Idea: selector-placeholder-pattern

### ISSUE THREAD

**Issue by mehcode** [kristerkari/stylelint-scss#26]
https://github.com/stylelint/stylelint/pull/1338

**Comment by kristerkari** [comment]
I guess we can create this since we already have other `-pattern` rules implemented.

**Comment by dryoma** [comment]
I made it working in a draft version, yet I have some minor doubts before pushing.

1. Placeholders could be used both in extends (`.foo { @extend %placeholder; }`) and in selectors, where they are defined (`%placeholder { color: #000; }`). Do we need to process all these cases, or maybe having an `includeDefinitions` optional param would be better? The arguments for the param would be a) parsing selectors would take longer, and b) if allplaceholders in `@extend` are forced to match a pattern then corresponding placeholder definitions will have to comply either.

1. Do we need options like [`resolveNestedSelectors`](http://stylelint.io/user-guide/rules/selector-class-pattern/#resolvenestedselectors-true--false-default-false)? I think it is quite obvious that selectors must be resolved to allow for code like this:
    ```scss
    %foo {
      &-mod { ... }
    }
    ```
    Yet stylelint's `selector-class-pattern` does have it.

**Comment by kristerkari** [comment]
> Placeholders could be used both in extends (.foo { @extend %placeholder; }) and in selectors, where they are defined (%placeholder { color: #000; }). Do we need to process all these cases, or maybe having an includeDefinitions optional param would be better?

I think that we should only validate the placeholder when it is defined. Isn't that what we do in the other rules too?

> Do we need options like resolveNestedSelectors? I think it is quite obvious that selectors must be resolved to allow for code like this:

That could be a good option to have, but probably not that critical for the first version of the rule.

**Comment by dryoma** [comment]
> I think that we should only validate the placeholder when it is defined. Isn't that what we do in the other rules too?

It makes perfect sense. Dunno why I was focusing `@extend` here at all :)
