### ISSUE TITLE
Rule idea: at-import-disallow-in-partials

### ISSUE THREAD

**Issue by dryoma** [kristerkari/stylelint-scss#28]
Importing partials from other partials can lead to difficulties following what is included where, and lead to mistakes of duplicate imports (met those just about a month ago). Grouping all `@import` commands in Sass bootstrap files (those that get compiled into .css) on the other hand may improve clarity as all the includes are in one place, and the order is clear and strict.

Hugo Giraudel [elaborates on the approach](https://sass-guidelin.es/#architecture) in a greater detail.

**Comment by kristerkari** [comment]
So would this rule check against `_` prefix in filename + `@import` inside the file?

**Comment by dryoma** [comment]
Indeed.

**Comment by kristerkari** [comment]
Implemented in #42
