### ISSUE TITLE
TypeError: Cannot read property 'mode' of undefined

### ISSUE THREAD

**Issue by mexn** [kristerkari/stylelint-scss#294]
Hi,

I guess I found a bug:
If I try to lint a file with the following content:
```
$breadcrumbs-item-separator-item-rtl: '\\';
$button-background: background('');
```
I get the this error: 
```
TypeError: Cannot read property 'mode' of undefined
    at findCommentsInRaws (node_modules/stylelint-scss/dist/utils/findCommentsInRaws.js:63:44)
    at checkRoot (node_modules/stylelint-scss/dist/rules/double-slash-comment-whitespace-inside/index.js:28:52)
    at exports.default (node_modules/stylelint-scss/dist/utils/eachRoot.js:14:5)
    at node_modules/stylelint-scss/dist/rules/double-slash-comment-whitespace-inside/index.js:19:25
    at Promise.resolve.then (node_modules/stylelint/lib/lintSource.js:230:9)
```

I narrowed it down a bit, so this only happens when the first value is the string with the two backslashes and when the second variable holds the result a function-call with a string as parameter. Any other combination seem to work properly.

**Comment by axelboc** [comment]
I'm seeing the same issue with rule `block-no-empty`

```
.../node_modules/stylelint/lib/rules/block-no-empty/index.js:50:47
```

**Comment by kristerkari** [comment]
@axelboc could you post the CSS here that triggers the error?

**Comment by axelboc** [comment]
Hmm, seems to be working fine now, strange. Sorry about that! I'll let you know if I bump into the issue again.
