### ISSUE TITLE
Rule idea: selector-no-redundant-parent

### ISSUE THREAD

**Issue by davidtheclark** [kristerkari/stylelint-scss#3]
Basically this: https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#unnecessaryparentreference

**Comment by kristerkari** [comment]
Good idea. :+1:  It will also be very helpful to look at scss-lint's implementation/tests to see how it is done.

- Linter: https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/unnecessary_parent_reference.rb
- Tests: https://github.com/brigade/scss-lint/blob/master/spec/scss_lint/linter/unnecessary_parent_reference_spec.rb
