### ISSUE TITLE
False positive for operator-no-unspaced with Rackspace URL

### ISSUE THREAD

**Issue by wulfharth** [kristerkari/stylelint-scss#308]
I'm getting a false positive for `operator-no-unspaced` with Rackspace URLs. The URLs contain a subdomain consisting of two hashes beginning with digits and separated by a hyphen. I can reproduce the bug with the following minimum test case.

**config**

    {
        "plugins": [ "stylelint-scss" ],
        "rules": { "scss/operator-no-unspaced": true }
    }

**.scss**

    div { background-image: url(https://99-0a.x.y.rackcdn.com/z.jpg); }

**output**

     1:35  ×  Expected single space before "/"   scss/operator-no-unspaced
     1:35  ×  Expected single space after "/"    scss/operator-no-unspaced
     1:36  ×  Expected single space before "/"   scss/operator-no-unspaced
     1:36  ×  Expected single space after "/"    scss/operator-no-unspaced

**Comment by kristerkari** [comment]
Thanks! I'll see if I can make a unit test to fail using your example

**Comment by kristerkari** [comment]
I opened a pull request with a fix:
https://github.com/kristerkari/stylelint-scss/pull/309

**Comment by kristerkari** [comment]
Fix released in v3.5.3:
https://github.com/kristerkari/stylelint-scss/releases/tag/3.5.3
