### ISSUE TITLE
warning " > stylelint-scss@3.5.4" has incorrect peer dependency "stylelint@^8.0.0 || ^9.0.0".

### ISSUE THREAD

**Issue by limonte** [kristerkari/stylelint-scss#317]
stylelint@10 has been released https://github.com/stylelint/stylelint/releases/tag/10.0.0

it would be nice to support it

**Comment by kristerkari** [comment]
Yup, I'll try to update all my stylelint plugin in the next couple of days. For now you can just ignore the warning.

**Comment by kristerkari** [comment]
This is now fixed in v3.6.0
