### ISSUE TITLE
scss/double-slash-comment-empty-line-before

### ISSUE THREAD

**Issue by Lesechka** [kristerkari/stylelint-scss#321]
Give me an advice please!
I have no idea with work of rule "scss/double-slash-comment-empty-line-before": "never".
If I type command 'npm run lint-style' I get mistakes:
src/styles/scss/_typography.scss
30:5 × Unexpected empty line before comment scss/double-slash-comment-empty-line-before
35:5 × Unexpected empty line before comment scss/double-slash-comment-empty-line-before.
But after command 'npm run fix-style' I get nothing.
Command "comment-empty-line-before": "never" works correctly, but I need to delete empty lines before double-slash comments

**Comment by kristerkari** [comment]
Hello @Lesechka 

I'm not sure what you mean by your message, but the  `always` option means that there should be always an empty line before the comment and `never` means that there should be no empty lines before the comments.

If it's possible for you to paste the contents of `_typography.scss` here, it would make it easier for me to help you.

**Comment by Lesechka** [comment]
I wrote rule "scss/double-slash-comment-empty-line-before": "never", but after command 'npm run fix-style' I get nothing. For example, in this part of code: 
h3 {
    
    // font-family: $fontStack;
    color: $textBlack;
    font-weight: 400;
    font-size: 24px;
    
    // font-weight: 700;
    line-height: 35px;
}
But after command 'npm run lint-style' I get mistakes, such as:
src/styles/scss/_typography.scss
30:5 × Unexpected empty line before comment scss/double-slash-comment-empty-line-before
35:5 × Unexpected empty line before comment scss/double-slash-comment-empty-line-before.

**Comment by kristerkari** [comment]
Thanks for the example! I'll write a test to see if there is something in the rule that is not working properly.

**Comment by Lesechka** [comment]
So the main my question: why the rule doesn't fix these mistakes? After fix command it should print these mistakes too, but it do nothing(
Thank you a lot!

**Comment by kristerkari** [comment]
> So the main my question: why the rule doesn't fix these mistakes? After fix command it should print these mistakes too, but it do nothing(
> Thank you a lot!

The rule has autofixing, but it might be not working correctly. I'll need to have a look at the rule and write a test using your example tonight after I finish working. 

In the meantime, please make sure that your `npm run fix-style` command is running `stylelint` with the `--fix` flag.

**Comment by Lesechka** [comment]
If I use rule "comment-empty-line-before": "never", npm run fix-style works correctly.

**Comment by Lesechka** [comment]
Unfortunately, almost the whole code of the project has double-slash comments. So I can't delete automatically empty lines before them with rule "comment-empty-line-before": "never"

**Comment by kristerkari** [comment]
I just checked the `double-slash-comment-empty-line-before` rule and there are not tests for the autofixing for `never` option, so maybe it was not implemented properly.

**Comment by Lesechka** [comment]
Also I should mention that in such case:
h1 {
    // font-family: $fontStack;
    line-height: 55px;
    @include mediaMobile {
        margin-bottom: 15px;
        font-size: 33px;
    }
}


//comment
h2 {
    // font-family: $fontStack;
    line-height: 45px;
    @include mediaMobile {
        font-size: 20px;
    }
}
Command 'npm run fix-style' works with '//comment'. But after every this command it deletes only one empty line.

**Comment by kristerkari** [comment]
I released v3.6.1 with some fixes. Please upgrade to that version and let me know if it fixes your problem:
https://github.com/kristerkari/stylelint-scss/releases/tag/3.6.1

**Comment by Lesechka** [comment]
Thank you for your help! It fixes my problem completely.
