### ISSUE TITLE
Disallow Undeclared Variables rule?

### ISSUE THREAD

**Issue by dartess** [kristerkari/stylelint-scss#328]
Hi!

What about Undeclared Variables?

Or there is no such rule, or I did not find it.

Example:

```
@import "./variables";

.some {
    $block: &;

    #{$block}__item {}    // must be OK, declared in this file.

    color: $color; // must be OK, declared in "./variables" and was imported.

    font-family: $font;  // Undefined variable.
}
```

The similar rule in eslint is called `no-undef`.

**Comment by kristerkari** [comment]
The idea is good, but it might just be difficult to implement. 

The rule would need to parse all the CSS files that your files are referencing to find the variables, and that might be very slow to do.

**Comment by dartess** [comment]
About slowness (imho):

When using tools that improve the quality of the code or, for example, reduce the size of the bundle code, the speed issue appears quite often. Suppose the rule is turned off by default, and its implementation will not affect the speed of work while it is turned off. Then the decision on what is more important, the speed of check or the accuracy of check, can be made individually by the developer.

_For example: I would agree to include this rule, if the check speed drops no more than twice._

And of course, if the implementation causes a slowdown of verification for all users, this rule is useless.

**Comment by kristerkari** [comment]
> For example: I would agree to enable this rule, if the check speed drops no more than twice.

I totally agree, but usually when there is reading from the disk + parsing involved, the performance drop is more like between 10x and 100x. There might of course be some tool (or even Sass?) that could do these kind of things in a very performant way.

**Comment by kristerkari** [comment]
There's also a similar discussion in this issue:
https://github.com/kristerkari/stylelint-scss/issues/276

**Comment by nex3** [comment]
In addition to performance, there's the issue of accurately resolving imports. Many applications pass load paths or custom importers to Sass which the linter won't have access to, without which accurately resolving imports to see which variables are defined in a given scope becomes essentially impossible.

**Comment by kristerkari** [comment]
> In addition to performance, there's the issue of accurately resolving imports. Many applications pass load paths or custom importers to Sass which the linter won't have access to, without which accurately resolving imports to see which variables are defined in a given scope becomes essentially impossible.

I think that with this comment it is enough to conclude that creating a rule like this does not make sense. For those who want to find unused variables, they can use a tool like this one:
https://github.com/XhmikosR/find-unused-sass-variables
