### ISSUE TITLE
Detect redundant combinators

### ISSUE THREAD

**Issue by twittwer** [kristerkari/stylelint-scss#335]
It would be nice if the `selector-no-redundant-nesting-selector` rule can detect the following scenario:
```scss
div & {
  &.selected {...}
}
```

Best Regards

**Comment by nex3** [comment]
This is just invalid Sass... `&` can't be used in a root-level selector.

**Comment by kristerkari** [comment]
@twittwer Thanks! Your example won't compile with Sass, so there is no need to try to detect it.
