### ISSUE TITLE
scss/* rules should not be processed on .css files

### ISSUE THREAD

**Issue by unikitty37** [kristerkari/stylelint-scss#352]
When using stylelint-scss, the SCSS-specific rules are applied to `.css` files as well, even when they do not make sense.

Example: setting `scss/comment-no-loud` to `true` results in being unable to have *any* comments in a `.css` file, as it rejects `/* … */` comments, but `// …` is not valid in a .css file.

Rather than having to set ignores for each `scss/*` rule in each `.css` file, it would be better if the `scss/*` rules didn't apply to non-SCSS files by default.

(I have no idea if stylelint actually supports this — apologies if this needs to be filed upstream rather than here…)

**Comment by kristerkari** [comment]
Thanks @unikitty37! I think that this might be a problem related to stylelint itself, the `stylelint-scss` plugin does not actually have control of to which files the rules are applied to.

**Comment by kristerkari** [comment]
Closing this as there is nothing that can be done about it here. Please open a new issue for stylelint's main repo if this is still a problem.
