### ISSUE TITLE
for loop crashes with vue + sass

### ISSUE THREAD

**Issue by akoidan** [kristerkari/stylelint-scss#380]
**package.json**:
```json
{
  "devDependencies": {
    "stylelint": "11.1.1",
    "stylelint-scss": "3.11.1"
  }
}
```

**App.vue**:
```vue
<template>
  <div>
  </div>
</template>

<script>
  export default {
  }
</script>
<style lang="sass" scoped>

  @for $i from 0 to 1
    $bar-h: 1

</style>
```

**.stylelintrc** (the rule is not relevant, just add something to trigger the linter):
```json
{
  "plugins": ["stylelint-scss"],
  "rules": {
    "selector-max-id": 0
  }
}

```

```bash
yarn install
./node_modules/.bin/stylelint "**.vue" 
```

```text
TypeError: Cannot read property 'start' of undefined
    at LocalFixer.node (/home/andrew/WebstormProjects/stylelint/node_modules/postcss-syntax/parse-style.js:35:27)
    at /home/andrew/WebstormProjects/stylelint/node_modules/postcss-syntax/parse-style.js:41:9
    at /home/andrew/WebstormProjects/stylelint/node_modules/postcss/lib/container.js:135:18
    at Root.each (/home/andrew/WebstormProjects/stylelint/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/home/andrew/WebstormProjects/stylelint/node_modules/postcss/lib/container.js:131:17)
    at LocalFixer.root (/home/andrew/WebstormProjects/stylelint/node_modules/postcss-syntax/parse-style.js:40:8)
    at LocalFixer.parse (/home/andrew/WebstormProjects/stylelint/node_modules/postcss-syntax/parse-style.js:69:9)
    at parseStyle (/home/andrew/WebstormProjects/stylelint/node_modules/postcss-syntax/parse-style.js:88:39)
    at /home/andrew/WebstormProjects/stylelint/node_modules/postcss-syntax/parse-style.js:103:17
    at Array.forEach (<anonymous>)
```

**Comment by kristerkari** [comment]
You probably need to run the linter with `--syntax sass` flag.

**Comment by akoidan** [comment]
Thanks for the response @kristerkari. I'm actually using stylelint-webpack-plugin. You can see the setup [here](https://github.com/akoidan/vue-webpack-typescript) so here're some facts:
 - If I introduce some linting issues in `.vue` files, lets say `color: #FFFFFF` stylelint will warn me on running the webpack
 - If I remove the plugin from `webpack.config.js` and leave the source with that issue, I won't get the warning, which means stylint does check sass files
 - But if I add 'syntax: 'sass',` custom parameter to StylelintWebpackPLugin, I will get the error for all vue files.

 1:1  ✖  Please check validity of the block starting from line #1   CssSyntaxError

Please note that stylelint [supports](https://vue-loader.vuejs.org/guide/linting.html#stylelint) vue files

**Comment by kristerkari** [comment]
Hmm.. I wonder if this is related to PostCSS' sass syntax parser, which I think might still be a bit of a work-in-progress.

**Comment by kristerkari** [comment]
Does the same work if you use SCSS to write Sass?

**Comment by akoidan** [comment]
Oh, it's not even related to stylelint-scss. I thought this was a syntax parser, rather than lint of rules. It breaks w/o this plugin.

**Comment by akoidan** [comment]
Moved conversation further to https://github.com/stylelint/stylelint/issues/4373
