### ISSUE TITLE
Undefined rule scss/no-duplicate-mixins

### ISSUE THREAD

**Issue by in-in** [kristerkari/stylelint-scss#383]
It seems this `no-duplicate-mixins` rule doesn't work properly.

VSCode: 1.39.0
vscode-stylelint (shinnn.stylelint): 0.51.0
stylelint-scss: 3.11.1

![192921571433510](https://user-images.githubusercontent.com/8797432/67129277-dfcd2580-f206-11e9-875f-0af0dd066b47.png)

**Comment by winterlamon** [comment]
I ran into the same error. After some investigation, it looks like `no-duplicate-mixins` just got merged to master on October 9, but that latest version (3.11.1) was released on September 21. So I imagine it will be available whenever the next release happens. Perhaps someone can shine some light on the release timeline.

**Comment by kristerkari** [comment]
I'll prepare the release now :)

**Comment by kristerkari** [comment]
it's realeased in 3.12.0: https://github.com/kristerkari/stylelint-scss/releases/tag/3.12.0
