### ISSUE TITLE
An asterisk in a @forward statement triggers scss/operator-no-unspaced

### ISSUE THREAD

**Issue by srawlins** [kristerkari/stylelint-scss#389]
See the prefix docs for `@forward`: https://sass-lang.com/documentation/at-rules/forward#adding-a-prefix:

```scss
@forward "src/list" as list-*;
```

> Content: Expected single space after "*" (scss/operator-no-unspaced)

**Comment by kristerkari** [comment]
Thanks! Seems like a bug.
