### ISSUE TITLE
`at-mixin-no-argumentless-call-parentheses` change behaviour

### ISSUE THREAD

**Issue by evilebottnawi** [kristerkari/stylelint-scss#39]
Rename `at-mixin-no-argumentless-call-parentheses` to `at-mixin-argumentless-call-parentheses` with options "always"/"never", i want use always `()` and control this in code. What do you think guys?

**Comment by dryoma** [comment]
I think it's a legit proposal. If noone minds, I'll take this up.

**Comment by kristerkari** [comment]
Sounds good!

**Comment by kristerkari** [comment]
I think that we should put this into a major release because it is a breaking change.

**Comment by dryoma** [comment]
Agreed.

**Comment by dryoma** [comment]
@kristerkari I pushed this one into a new branch https://github.com/kristerkari/stylelint-scss/tree/2.0.0/at-mixin-argumentless-call-parentheses for now. Shall we create new branches for all other such cases (like rules for the specified release), or rather merge them in one `x.x.x` branch? Also, not sure how to label this issue now %)

**Comment by kristerkari** [comment]
I think that we can have separate branches for each feature, open PRs, and then just merge them when we are ready to release.

**Comment by dryoma** [comment]
The way we ended up pushing `at-import-partial-extension-blacklist` and `-whitelist` and deprecated `at-import-no-partial-extension` lead me to a suggestion: shall we do the same here? I mean create the new rule (`"always"/"never"`) and deprecate the old one for now (and remove it in 2.0.0)?

**Comment by kristerkari** [comment]
@dryoma yeah we could do that.

**Comment by jeddy3** [comment]
> I mean create the new rule ("always"/"never") and deprecate the old one for now (and remove it in 2.0.0)?

Yep, sounds good. In stylelint we [have the convention](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/about-rules.md#no-rules) that something is a `-no-` rule *only if* it makes *no sense what-so-ever* to want to enforce the opposite as a convention. For example, `block-no-empty` where the opposite is to enforce that *every block must be empty*.

So, if there's even just an inkling of a feeling that someone would want to enforce the opposite, then I recommend creating a non `-no-` rule with options.

**Comment by dryoma** [comment]
Ok, so the new rule is pushed to master (will be released in NPM with 1.3.0). The old one is deleted in `2.0.0/at-mixin-argumentless-call-parentheses` branch.

Closing this for now.
