### ISSUE TITLE
Add a lint for using global function names

### ISSUE THREAD

**Issue by nex3** [kristerkari/stylelint-scss#397]
Now that the module system has launched, functions that are available from modules should be called using those modules rather than using their global aliases. The canonical list of which functions have moved to which modules is [in the module system proposal](https://github.com/sass/sass/blob/master/accepted/module-system.md#built-in-modules-1).

Maybe the lint should also link to the [Sass migrator documentation](https://sass-lang.com/documentation/cli/migrator) to help users migrate automatically?

cc @rambleraptor

**Comment by kristerkari** [comment]
New rule released in v3.16.0:
https://github.com/kristerkari/stylelint-scss/releases/tag/3.16.0
