### ISSUE TITLE
Remove babel

### ISSUE THREAD

**Issue by XhmikosR** [kristerkari/stylelint-scss#400]
I can't see any reason to keep using babel if you target modern Node.js versions and should simplify things a lot. Also, jest should work out of the box IIRC with import/exports.

Feel free to ping me if anyone makes a WIP branch :)

**Comment by kristerkari** [comment]
That's correct. Babel is in use because the ES2015 support was not that good in Node.js still a few years ago.

I'm fine with removing it, if it does not cause any compatibility issues that can not easily be solved.

**Comment by XhmikosR** [comment]
I'm not sure how to proceed with the imports/exports. I have a WIP (broken) branch [here](https://github.com/kristerkari/stylelint-scss/compare/master...XhmikosR:rm-babel) but things will need to change.

So maybe it's time for a 4.0.0 release where we do this and the other breaking changes? BTW let me know if you have any suggestions how to solve the exports issue.

**Comment by XhmikosR** [comment]
I think only the utils are left in my branch. Let me know if I should continue with this. IMO it's definitely a good move since it makes things cleaner.

**Comment by kristerkari** [comment]
Hmm... there are some things ready to review and publish, so maybe it's better to get this repository to a bit cleaner state before releasing 4.0.0. During the Christmas time could be a good moment to do it.

Removing Babel does not bring much benefit for the end user, so it should not be a high priority for now.

**Comment by XhmikosR** [comment]
Yeah, sure. I just want us to get it done, especially since I've done most of the changes :)

That being said, I'd say let's get the other PRs merged and you release a new version for now.

**Comment by XhmikosR** [comment]
On a side note, this isn't a development only thing. The final dist size will decrease (not a lot, but still) and there might be a slight improvement in the module load time.

**Comment by XhmikosR** [comment]
Alright, I fixed all issues in my branch above minus one which I cannot figure out. Not sure how to import postcss-media-query-parser.

**Comment by XhmikosR** [comment]
Fixed in the v4 branch.
