### ISSUE TITLE
add new excludeExtensions blacklist option for `at-import-no-partial-extension`

### ISSUE THREAD

**Issue by rob3c** [kristerkari/stylelint-scss#41]
Rule `at-import-no-partial-extension` currently isn't very useful when namespacing files like `foo.bar.scss`, `foo.baz.scss`, etc. That's because stylelint-scss sees an import like

`@import "foo.bar";` // <-- bar should not be flagged as an extension here

as having extension `bar` instead of recognizing that it isn't using a common `.scss`, `.less`, etc. known extension and ignoring it.

The stylelist-scss API can handle this, in principle, since you can pass blacklist `RegExp`s like `/^(?!scss)/` in the `ignoreExtensions` array when using the API in javascript. However, the JSON format used by `.stylelistrc` doesn't support `RegExp`s natively and only allows strings.

Rather than try to have stylelist-scss figure out what's a string vs a regex, I think the most direct way to address this would be to add a new config option `excludeExtensions` that would act as an extension blacklist similar to how `ignoreExtensions` acts as a whitelist.

**Comment by dryoma** [comment]
To be honest, I did think about this use case, but decided to leave it for later. So no excuse to chill now :)

**Comment by dryoma** [comment]
What if we split this one into two rules: `at-import-partial-extension-blacklist` and `at-import-partial-extension-whitelist` instead of two options to a "binary" rule? Will this be too much fragmentation?

@jeddy3 @kristerkari what do you think?

**Comment by jeddy3** [comment]
> What if we split this one into two rules: at-import-partial-extension-blacklist and at-import-partial-extension-whitelist instead of two options to a "binary" rule? Will this be too much fragmentation?

I think that's the most idiomatic way to go about this.

**Comment by kristerkari** [comment]
Done in https://github.com/kristerkari/stylelint-scss/pull/46

**Comment by rob3c** [comment]
Thanks for adding this! It looks like you've also addressed issues with URIs and url() that I hadn't originally considered but make perfect sense.
