### ISSUE TITLE
Stylelint v13 support

### ISSUE THREAD

**Issue by gussyboy** [kristerkari/stylelint-scss#433]
Can you please add support for stylelint v13

**Comment by ntwb** [comment]
See #428

**Comment by kristerkari** [comment]
Yeah sorry about the delay. I've been really busy for the last couple of weeks with no time for open source. Now I have time to catch up :)

**Comment by kristerkari** [comment]
New version out with stylelint 13 support:
https://github.com/kristerkari/stylelint-scss/releases/tag/3.14.0
