### ISSUE TITLE
npm-warning for "stylelint" peer dependency

### ISSUE THREAD

**Issue by jens-duttke** [kristerkari/stylelint-scss#441]
Right now, npm throws a warning:

> stylelint-scss@3.13.0 requires a peer of stylelint@^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0 but none is installed. You must install peer dependencies yourself.

Currently, stylelint 13.0.0 is the latest version.

I'm using:
```
"stylelint": "13.0.0",
"stylelint-scss": "3.13.0"
```

**Comment by Didel** [comment]
+1
