### ISSUE TITLE
Complains on @use @mixin @include

### ISSUE THREAD

**Issue by crystalfp** [kristerkari/stylelint-scss#456]
Stylelint complains about these: `@use @mixin @include`
It makes no difference if I add the `-s scss` command line option to stylelint.
And yes, I have added "stylelint-scss" to the plugins section in .stylelintrc
Thanks for helping!

mario

**Comment by crystalfp** [comment]
Even if I removed the `at-rule-no-unknown` rule, it seems imported by `stylelint-config-recommended` but definitely they are not unknown at rules!

**Comment by kristerkari** [comment]
Please have a look at the readme of the rule for a solution:
https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/at-rule-no-unknown/README.md#at-rule-no-unknown


```json
{
  "rules": {
    "at-rule-no-unknown": null,
    "scss/at-rule-no-unknown": true
  }
}
```
