### ISSUE TITLE
Rule idea: scss/comment-whitespace-inside and scss/comment-empty-line-before

### ISSUE THREAD

**Issue by danny-andrews** [kristerkari/stylelint-scss#48]
The standard comment-whitespace-inside and comment-emptly-line-before rules only work with standard css comments (e.g. `/* Comment */` [note](https://github.com/stylelint/stylelint/issues/1049#issuecomment-208857356)), so we should add a rule which checks these things for scss comments (e.g. `// Comment`).

**Comment by dryoma** [comment]
Thanks, definitely a must.

**Comment by dryoma** [comment]
Published with 1.3.0.
