### ISSUE TITLE
Override stylelint's at-rule-no-unkown by default

### ISSUE THREAD

**Issue by theahmadzai** [kristerkari/stylelint-scss#489]
Every time you have to include stylelint-scss plugin these lines are mandatory 

```javascript
rules: {
    'at-rule-no-unknown': null,
    'scss/at-rule-no-unknown': true,
  },
```

can this configuration be provided by default by stylelint-scss plugin?

**Comment by kristerkari** [comment]
Thanks @theahmadzai  ! Doing that would mean that we would enable `scss/at-rule-no-unknown` for everyone by default, which does not make sense. Anyone can create their own shareable stylelint configs that include the configuration that you mentioned.
