### ISSUE TITLE
[Request] `no-duplicate-dollar-variables` to take !default into consideration

### ISSUE THREAD

**Issue by joseph118** [kristerkari/stylelint-scss#500]
Currently, the rule doesn't consider the default keyword and throws a lint error when the following scenario is present;
```
$a: () !default;
$a: map-merge($defaults, $a);
```

I believe that the rule should at least be configurable and considers duplicate with default keyword to an extent

**Comment by kristerkari** [comment]
Closing as this was fixed in #502 👍
