### ISSUE TITLE
Default `string-quotes` rule and Sass modules

### ISSUE THREAD

**Issue by niksy** [kristerkari/stylelint-scss#508]
It seems like default `string-quotes` rule ignores Sass Modules at-rules `@use` and `@forward`. Is this something that should be supported in this package or should I report this to Stylelint repo? It seems there’s a [bunch of checks for non-standard configurations](https://github.com/stylelint/stylelint/blob/master/lib/rules/string-quotes/index.js) so I don’t know if that relates to Sass modules.

**Comment by kristerkari** [comment]
This is something that stylelint should take care of since it's their rule. I also don't want to create new rules to this repo only because of some edge cases like that.
