### ISSUE TITLE
Rule idea: Disallow @import

### ISSUE THREAD

**Issue by dsimon-onventis** [kristerkari/stylelint-scss#510]
According to the [Sass documentation](https://sass-lang.com/documentation/at-rules/import), you should no longer use the `@import` rule:

> The Sass team discourages the continued use of the `@import` rule. Sass will gradually phase it out over the next few years, and eventually remove it from the language entirely. Prefer the `@use` rule instead.

It would be very useful to have a rule, which disallows the usage of the `@import` rule.

**Comment by stof** [comment]
isn't it already what the `partial-no-import` does ?

**Comment by stof** [comment]
hmm, no. `partial-no-import` runs only inside partials. so what's wanted is almost the same implementation, but not exactly.

**Comment by json-derulo** [comment]
Like described in #512, this can be done with stylelint's rule [`at-rule-disallowed-list`](https://github.com/stylelint/stylelint/blob/master/lib/rules/at-rule-disallowed-list/README.md). There is no need for an additional rule.
