### ISSUE TITLE
no-invalid-position-at-import-rule fails with @at-root

### ISSUE THREAD

**Issue by kraftner** [kristerkari/stylelint-scss#531]
Somewhat related to #524 

Maybe this rule should just be disabled for stylelint-scss according to https://github.com/stylelint/stylelint/issues/5133#issuecomment-834466368

**Comment by kristerkari** [comment]
Thanks! I did not check in #524 what the rule in question was, but since the rule is from the core stylelint package and not stylelint-scss, the only way is for the user to manually enable/disable the rule. There is nothing that I can do about it.

**Comment by kraftner** [comment]
Oh, sorry, I'm still somewhat new to stylelint and wasn't aware that as a plugin you can't disable rules from elsewhere. Thanks for explaining - I've now disabled it in my config.
