### ISSUE TITLE
no-browser-hacks showing $ and !default as errors

### ISSUE THREAD

**Issue by s10wen** [kristerkari/stylelint-scss#60]
Maybe you can help with this please?
https://github.com/stylelint/stylelint/issues/1710

Regarding:
https://github.com/stylelint/stylelint/blob/master/src/rules/no-browser-hacks/README.md

I'm getting errors for $colour-alpha and !default which is valid Sass code.

Appreciate this is a Sass specific question, but wondering if there's a way to whitelist $ and !default for this rule please?

**Comment by dryoma** [comment]
I'm afraid we can't help at the moment, as our ruleset has nothing to do with that rule or stylehacks tool that it is using. So for `no-browser-hacks` to support nested rules and stuff like you mentioned, stylehacks itself should be updated.

**Comment by s10wen** [comment]
@ben-eb wondering if you can help with this, or point me in the right direction please?

**Comment by ben-eb** [comment]
Indeed, stylehacks was designed for working with CSS files. I'd be happy to accept a PR for an optional `scssCompatibility` flag which could handle these exceptions.

**Comment by s10wen** [comment]
Ah, it wasn't immediately obvious to me that it was using https://github.com/ben-eb/stylehacks I'll have a play, cheers.

**Comment by s10wen** [comment]
Had a play, here's a solution I've come up with (it's pretty terrible, but works for what I'm after);

`leadingStar.js` => delete `!_$_`
`index.js` => delete the references to `important`

Another solution is to simply run as is, then do a find + delete for the CSS specific results you're not interested in within the results.

@ben-eb thanks for the help, I know the logic for what I'm after (above), but I'm not proficient enough at JS to understand how to wrap that code for a conditional flag. If I get the time I'll ask some of my JS friends to help me go over it, cheers!

**Comment by dryoma** [comment]
I suppose it'd be better to discuss stylehack's logic in [stylehack's issues](https://github.com/ben-eb/stylehacks/issues) ;)

Closing this.
