### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by evilebottnawi** [kristerkari/stylelint-scss#64]
```shell
TypeError: Cannot read property '1' of null
    at findCommentsInRaws (/path/to//node_modules/stylelint-scss/dist/utils/findCommentsInRaws.js:144:34)
    at /path/to//node_modules/stylelint-scss/dist/rules/double-slash-comment-whitespace-inside/index.js:18:50
    at /path/to//node_modules/stylelint/dist/postcssPlugin.js:134:46
    at Array.forEach (native)
    at /path/to//node_modules/stylelint/dist/postcssPlugin.js:113:33
```

Got this error on:
```scss
/*!
 *  Font Awesome 4.6.3 by @davegandy - http://fontawesome.io - @fontawesome
 *  License - http://fontawesome.io/license (Font: SIL OFL 1.1, CSS: MIT License)
 */
```

and

```scss
/* Example with animate.css
@import "animate.css/source/_base.css";
@import "animate.css/source/fading_entrances/fadeIn.css";
*/
```
Got this error on rules:
- `partial-no-import`
- `double-slash-comment-empty-line-before`
- `double-slash-comment-inline`
- `double-slash-comment-whitespace-inside`
- `operator-no-newline-after`
- `operator-no-newline-before`
- `operator-no-unspaced`

**Comment by dryoma** [comment]
Wow, thanks.

**Comment by dryoma** [comment]
Please update to 1.3.1 and see if it is fixed for you.

**Comment by evilebottnawi** [comment]
@dryoma thanks! I'm going to try now

**Comment by evilebottnawi** [comment]
@dryoma 
The error still occurs:
```shell
TypeError: Cannot read property '1' of null
    at findCommentsInRaws (/home/itgalaxy/web/dev0.cms.dev.itgalaxy.company/public_html/wp-content/themes/insteria/node_modules/stylelint-scss/dist/utils/findCommentsInRaws.js:76:123)
    at /home/itgalaxy/web/dev0.cms.dev.itgalaxy.company/public_html/wp-content/themes/insteria/node_modules/stylelint-scss/dist/rules/double-slash-comment-whitespace-inside/index.js:18:50
    at /home/itgalaxy/web/dev0.cms.dev.itgalaxy.company/public_html/wp-content/themes/insteria/node_modules/stylelint/dist/postcssPlugin.js:134:46
    at Array.forEach (native)
    at /home/itgalaxy/web/dev0.cms.dev.itgalaxy.company/public_html/wp-content/themes/insteria/node_modules/stylelint/dist/postcssPlugin.js:113:33
```

**Comment by evilebottnawi** [comment]
@dryoma 
On this:
```scss
.dropdown-menu:not(.level-0) {
  margin: 0;

  a {
    white-space: normal;
  }
}
```

**Comment by evilebottnawi** [comment]
@dryoma maybe best ignore comments between selectors, property values, etc? In `stylelint` we add note to docs about it and wait postcss v6, regexp not good solution for parsing scss, css and etc, i think we will get a lot of issues using reg exp to parse code and it will just be a headache :sob: This is just my opinion.

**Comment by dryoma** [comment]
First off, sorry for the inconvenience.

The regexes are actually not so much of a problem - I just missed a couple of cases; neede more tests, but 'IT happens. The thing here seems to be [PostCSS itself](https://github.com/postcss/postcss/issues/859); trying to figure out who's on the wrong here.

As for the comments: we *really* need to parse them as in SCSS missing //-comments seems a major fault. Not to mention that we have a rule specifically for requiring/prohibiting all comments to be inline. So if it is possible to fix all those, I'd definitely try to do so (unless it takes too long).

**Comment by dryoma** [comment]
@evilebottnawi please see if the new patch fixed the issue for you.

**Comment by evilebottnawi** [comment]
@dryoma works fine, thanks for fast fixes :smile:
