### ISSUE TITLE
Rule idea: dollar-variable-pattern

### ISSUE THREAD

**Issue by arnaudvalle** [kristerkari/stylelint-scss#8]
Following my question on SO (http://stackoverflow.com/questions/36304921) I'm proposing to add a rule to enforce a naming convention for variable names in SCSS.

Something like https://github.com/sasstools/sass-lint/pull/257 would be great I reckon, where we could either specify a string for a preferred common format (camelcase, snakecase etc...) or a custom pattern.

For example I may want my variable names to always be camel case, in which case:

```
// this wouldn't be correct
$my-variable: #000;

// but this would be correct
$myVariable: #000;
```
I don't have experience in writing plugins for stylelint but I may give it a try based on the other rules in this repo and try to work something out in a PR if it's of any use to anybody else.

**Comment by jeddy3** [comment]
> I don't have experience in writing plugins for stylelint but I may give it a try

Hi @arnaudvalle. I'm not a contributor here, but I help out on the `stylelint` linter itself. Perhaps I can be of some help here...

There's some stylelint documentation that you might find useful when getting started: [working on rules](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md) & [writing plugins](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md).

There's also some documentation on [naming rules](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#about-rule-names) and [how rules are built to work together](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#rules-work-together).

Finally, there are a handful of similar `*-pattern` rules in stylelint that might provide a good starting point this plugin:

* [`custom-property-pattern`](https://github.com/stylelint/stylelint/blob/master/src/rules/custom-property-pattern/) - probably the most similar to this proposed plugin.
* [`custom-media-pattern`](https://github.com/stylelint/stylelint/tree/master/src/rules/custom-media-pattern)
* [`selector-class-pattern`](https://github.com/stylelint/stylelint/tree/master/src/rules/selector-class-pattern)

...

You might want to follow the same convention and call this plugin `variable-pattern`?

Good luck :)

**Comment by arnaudvalle** [comment]
@jeddy3 thanks for the links, they'll definitely be useful when I have a go at this!

**Comment by kristerkari** [comment]
Thanks! This is something that should not be that hard to implement.

**Comment by jeddy3** [comment]
You'll probably want to call this plugin: `stylelint-dollar-variable-pattern` so that the [precss](https://github.com/jonathantneal/precss) can use it too :)

**Comment by kristerkari** [comment]
Yeah, if the rule is not going to be only used for scss syntax, then it makes sense to make it a plugin and just wrap it in stylelint-scss.

**Comment by kristerkari** [comment]
This was implemented in #10, so closing. Thanks to everyone who participated!

**Comment by Arcanorum** [comment]
I think the docs for this need updating. No mention of how to use this. https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/dollar-variable-pattern/README.md

**Comment by Arkkimaagi** [comment]
@Arcanorum if you or someone else have not solved this already, I had luck by adding this to my .stylelintrc.yaml in the rules part:
```
scss/dollar-variable-pattern: "^-?[a-z][a-z0-9]*(--?[a-z0-9]+)*$"
```
